name: StateCraft
version: 0.0.1
author: Andrew Kim
main: edu.brown.cs.ykim81.statecraft.Main
depend: [Vault]
commands:
  sc:
    description: Your description
    usage: Command not found. Type /sc help for a list of commands.